projects:
  makebelieve:
    schemaPath: amplify/graphql/schema.json
    includes:
      - amplify/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: amplify/API.ts
        docsFilePath: amplify/graphql
extensions:
  amplify:
    version: 3
